name: Action Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Await a workflow
        uses: ./
        with:
          token: ${{ github.token }}
          workflow: sleep.yml
          check_name: short
          timeout_mins: 5
          poll_interval_ms: 10000 # 10 seconds
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Await a workflow
        uses: ./
        with:
          token: ${{ github.token }}
          workflow: sleep.yml
          timeout_mins: 5
          poll_interval_ms: 10000 # 10 seconds
